### ISSUE TITLE
大佬您好，请问能添加docker部署吗

### ISSUE THREAD

**Issue by candies404** [vaebe/kkdl-go#1]

**Comment by vaebe** [comment]
已经修改 docker 打包的相关配置目前本地打包后可正常使用

1. 执行 `make image` 命令进行打包,输出如下

<img width="1375" alt="image" src="https://github.com/vaebe/kkdl-go/assets/52314078/c13f77df-0c21-475e-a1fc-030682f44749">

3. 启动镜像

<img width="1431" alt="image" src="https://github.com/vaebe/kkdl-go/assets/52314078/8b3775b4-3f77-4efa-8f57-e5b23e67b74a">

4. 填写相关配置后点击 run

<img width="616" alt="image" src="https://github.com/vaebe/kkdl-go/assets/52314078/9e72d488-d4f0-4ea9-a838-0365d98dbcb6">

5. 启动成功后输出如下: 端口映射 6001
<img width="1431" alt="image" src="https://github.com/vaebe/kkdl-go/assets/52314078/f8c9ab4e-211e-4332-8218-21f1651d6b07">
